# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180527_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitsusers',
            name='phone',
            field=models.CharField(blank=True, default=110, max_length=11, verbose_name='电话'),
        ),
    ]
