# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180426_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodels',
            name='sex',
            field=models.CharField(choices=[('man', '男'), ('women', '女')], default=1, max_length=20, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
