# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 10:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('c_price', models.FloatField(verbose_name='商品价格')),
                ('c_comfrom', models.CharField(max_length=100, verbose_name='商品产地')),
                ('c_images', models.ImageField(default='df_goods/fruit.jpg', upload_to='df_goods/', verbose_name='商品图片')),
                ('c_unit', models.CharField(max_length=50, verbose_name='单位/斤')),
                ('c_desc', models.CharField(max_length=255, verbose_name='诱惑')),
                ('c_content', DjangoUeditor.models.UEditorField(default='', verbose_name='商品描述')),
                ('c_stock', models.IntegerField(verbose_name='商品库存')),
                ('c_click', models.IntegerField(verbose_name='商品点击率')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='CommOrders',
            fields=[
                ('o_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='订单号')),
                ('o_date', models.DateTimeField(auto_now_add=True, verbose_name='订单时间')),
                ('o_money', models.CharField(max_length=200, verbose_name='订单价格')),
                ('o_type', models.BooleanField(choices=[(True, '已支付'), (False, '未支付')])),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CommTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=20, verbose_name='商品标签')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='CommType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='商品分类')),
                ('type_img', models.ImageField(upload_to='df_type/', verbose_name='商品分类图片')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='订单商品数量')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 'orderinfo',
            },
        ),
        migrations.CreateModel(
            name='ShopCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_num', models.IntegerField(verbose_name='购买的数量')),
                ('s_money', models.FloatField(verbose_name='商品总价')),
                ('comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.CommInfo', verbose_name='商品种类')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'cart',
            },
        ),
    ]
