# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_auto_20180527_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commorders',
            name='o_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单号'),
        ),
    ]
