# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_title', models.CharField(max_length=100, verbose_name='商品名称')),
                ('g_pic', models.ImageField(default='df_goods/default.jpg', upload_to='df_goods/%Y/%m', verbose_name='商品图片')),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('g_unit', models.CharField(max_length=50, verbose_name='计量单位')),
                ('g_click', models.IntegerField(verbose_name='浏览次数')),
                ('g_desc', models.CharField(max_length=150, verbose_name='商品描述')),
                ('g_stock', models.IntegerField(verbose_name='库存数量')),
                ('g_content', models.TextField(verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='分类名称')),
                ('class_name', models.CharField(default='', max_length=50, verbose_name='')),
                ('type_img', models.ImageField(default='df_type/default.jpg', upload_to='df_type/%Y/%m/', verbose_name='分类封面图')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.AddField(
            model_name='goodinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo'),
        ),
    ]
